"""
PDF generation service using ReportLab.

Generates professionally formatted, print-ready PDFs for:
- RTI applications
- Complaint letters

All PDFs are saved under backend/generated_pdfs/<uuid>.pdf and the path is
returned so it can be stored in the DB and served via a download endpoint.
"""
import os
import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.lib.enums import TA_JUSTIFY, TA_CENTER, TA_LEFT
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib import colors

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PDF_DIR = os.path.join(BASE_DIR, "generated_pdfs")
os.makedirs(PDF_DIR, exist_ok=True)

BRAND_BLUE = colors.HexColor("#2563EB")
SOFT_GRAY = colors.HexColor("#F3F4F6")


def _get_styles():
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name="NMTitle", fontSize=16, leading=20, textColor=BRAND_BLUE, fontName="Helvetica-Bold", spaceAfter=4, alignment=TA_CENTER))
    styles.add(ParagraphStyle(name="NMSubtitle", fontSize=9, leading=12, textColor=colors.gray, alignment=TA_CENTER, spaceAfter=14))
    styles.add(ParagraphStyle(name="NMHeading", fontSize=11, leading=14, textColor=BRAND_BLUE, fontName="Helvetica-Bold", spaceBefore=10, spaceAfter=6))
    styles.add(ParagraphStyle(name="NMBody", fontSize=10.5, leading=16, alignment=TA_JUSTIFY, fontName="Helvetica", spaceAfter=8))
    styles.add(ParagraphStyle(name="NMBodyLeft", fontSize=10.5, leading=15, alignment=TA_LEFT, fontName="Helvetica"))
    styles.add(ParagraphStyle(name="NMFooter", fontSize=8, leading=10, textColor=colors.gray, alignment=TA_CENTER))
    return styles


def _header_footer(canvas, doc):
    canvas.saveState()
    # Top brand bar
    canvas.setFillColor(BRAND_BLUE)
    canvas.rect(0, A4[1] - 8 * mm, A4[0], 8 * mm, fill=1, stroke=0)
    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 10)
    canvas.drawString(15 * mm, A4[1] - 6 * mm, "NyayaMitra AI")
    canvas.setFont("Helvetica", 8)
    canvas.drawRightString(A4[0] - 15 * mm, A4[1] - 6 * mm, "Know your rights. Generate documents. Take action.")

    # Footer
    canvas.setFillColor(colors.gray)
    canvas.setFont("Helvetica", 7.5)
    footer_text = f"Generated by NyayaMitra AI on {datetime.date.today().strftime('%d %B %Y')} — This document is a citizen-drafted aid, not a substitute for professional legal advice."
    canvas.drawCentredString(A4[0] / 2, 10 * mm, footer_text)
    canvas.restoreState()


def generate_rti_pdf(doc_id: str, applicant_name: str, applicant_address: str, applicant_contact: str,
                      department: str, location: str, subject: str,
                      information_requested: list, grounds: str, fee_note: str) -> str:
    filepath = os.path.join(PDF_DIR, f"rti_{doc_id}.pdf")
    styles = _get_styles()
    doc = SimpleDocTemplate(filepath, pagesize=A4,
                             topMargin=20 * mm, bottomMargin=18 * mm,
                             leftMargin=20 * mm, rightMargin=20 * mm)
    story = []

    story.append(Paragraph("APPLICATION UNDER THE RIGHT TO INFORMATION ACT, 2005", styles["NMTitle"]))
    story.append(Paragraph("Filed under Section 6(1) of the RTI Act, 2005", styles["NMSubtitle"]))
    story.append(Spacer(1, 6))

    story.append(Paragraph("To,", styles["NMBodyLeft"]))
    story.append(Paragraph(f"The Public Information Officer (PIO)<br/>{department}<br/>{location}", styles["NMBodyLeft"]))
    story.append(Spacer(1, 10))

    story.append(Paragraph(f"<b>Subject:</b> {subject}", styles["NMHeading"]))

    story.append(Paragraph("Respected Sir/Madam,", styles["NMBody"]))
    story.append(Paragraph(
        "Under Section 6(1) of the Right to Information Act, 2005, I hereby request the following "
        "information/documents from your office:", styles["NMBody"]))

    for i, point in enumerate(information_requested, start=1):
        story.append(Paragraph(f"{i}. {point}", styles["NMBody"]))

    if grounds:
        story.append(Paragraph("<b>Grounds for seeking this information:</b>", styles["NMHeading"]))
        story.append(Paragraph(grounds, styles["NMBody"]))

    story.append(Paragraph("<b>Prescribed Fee:</b>", styles["NMHeading"]))
    story.append(Paragraph(fee_note, styles["NMBody"]))

    story.append(Paragraph(
        "I request that the information be provided to me within 30 days as mandated under Section 7(1) "
        "of the RTI Act, 2005, failing which I reserve the right to file a First Appeal under Section 19.",
        styles["NMBody"]))

    story.append(Spacer(1, 14))
    story.append(Paragraph("Yours faithfully,", styles["NMBodyLeft"]))
    story.append(Spacer(1, 20))

    applicant_table = Table(
        [["Name of Applicant:", applicant_name],
         ["Address:", applicant_address],
         ["Contact Number:", applicant_contact or "—"],
         ["Date:", datetime.date.today().strftime("%d-%m-%Y")]],
        colWidths=[42 * mm, 118 * mm],
    )
    applicant_table.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("TEXTCOLOR", (0, 0), (0, -1), BRAND_BLUE),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 2),
    ]))
    story.append(applicant_table)

    doc.build(story, onFirstPage=_header_footer, onLaterPages=_header_footer)
    return filepath


def generate_complaint_pdf(doc_id: str, complaint_type: str, applicant_name: str, applicant_address: str,
                            applicant_contact: str, recipient_name: str, recipient_address: str,
                            subject: str, opening_paragraph: str, body_paragraphs: list,
                            desired_resolution_paragraph: str, closing_paragraph: str,
                            relevant_law_reference: str) -> str:
    filepath = os.path.join(PDF_DIR, f"complaint_{doc_id}.pdf")
    styles = _get_styles()
    doc = SimpleDocTemplate(filepath, pagesize=A4,
                             topMargin=20 * mm, bottomMargin=18 * mm,
                             leftMargin=20 * mm, rightMargin=20 * mm)
    story = []

    type_label = {
        "consumer": "CONSUMER COMPLAINT LETTER",
        "landlord": "LANDLORD / SECURITY DEPOSIT COMPLAINT LETTER",
        "workplace": "WORKPLACE GRIEVANCE LETTER",
        "municipal": "MUNICIPAL COMPLAINT LETTER",
    }.get(complaint_type, "FORMAL COMPLAINT LETTER")

    story.append(Paragraph(type_label, styles["NMTitle"]))
    story.append(Paragraph(f"Reference: {relevant_law_reference}", styles["NMSubtitle"]))
    story.append(Spacer(1, 6))

    story.append(Paragraph(f"From:<br/>{applicant_name}<br/>{applicant_address}<br/>{applicant_contact or ''}", styles["NMBodyLeft"]))
    story.append(Spacer(1, 8))
    story.append(Paragraph(f"To,<br/>{recipient_name}<br/>{recipient_address or ''}", styles["NMBodyLeft"]))
    story.append(Spacer(1, 8))
    story.append(Paragraph(f"Date: {datetime.date.today().strftime('%d-%m-%Y')}", styles["NMBodyLeft"]))
    story.append(Spacer(1, 10))

    story.append(Paragraph(f"<b>Subject:</b> {subject}", styles["NMHeading"]))
    story.append(Paragraph("Dear Sir/Madam,", styles["NMBody"]))
    story.append(Paragraph(opening_paragraph, styles["NMBody"]))

    for para in body_paragraphs:
        story.append(Paragraph(para, styles["NMBody"]))

    story.append(Paragraph("<b>Resolution Sought:</b>", styles["NMHeading"]))
    story.append(Paragraph(desired_resolution_paragraph, styles["NMBody"]))

    story.append(Paragraph(closing_paragraph, styles["NMBody"]))

    story.append(Spacer(1, 16))
    story.append(Paragraph("Yours sincerely,", styles["NMBodyLeft"]))
    story.append(Spacer(1, 16))
    story.append(Paragraph(applicant_name, styles["NMBodyLeft"]))
    story.append(Paragraph(applicant_contact or "", styles["NMBodyLeft"]))

    doc.build(story, onFirstPage=_header_footer, onLaterPages=_header_footer)
    return filepath
